minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - typescript-eslint
  - '@typescript-eslint/*'
  - eslint
  - '@eslint/*'
  - eslint-plugin-vue

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
peerDependencyRules:
  allowedVersions:
    eslint-plugin-jest>eslint: ^10.0.0
    eslint-plugin-vuejs-accessibility>eslint: ^10.0.0
