minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - typescript-eslint
  - '@typescript-eslint/*'
  - eslint
  - '@eslint/*'
  - eslint-plugin-vue

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
